apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: easy-deploy-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: easy-deploy-operator
subjects:
  - kind: ServiceAccount
    name: easy-deploy-operator
    namespace: easy-deploy-system

