apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace | quote }}
  {{- if .Values.traffic }}
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint
  {{- end }}
