apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crd/birservice_crd.yaml
  - operator/namespace.yaml
  - operator/serviceaccount.yaml
  - operator/clusterrole.yaml
  - operator/clusterrolebinding.yaml
  - operator/deployment.yaml
  - registry/namespace.yaml
  - registry/deployment.yaml
  - registry/service.yaml
  - gateway/gateway.yaml
  - gateway/reference-grants.yaml
  - gateway/cluster-issuer.yaml
  - gateway/grafana-route.yaml

