apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../config/crd/birservice_crd.yaml
  - operator/namespace.yaml
  - operator/serviceaccount.yaml
  - operator/clusterrole.yaml
  - operator/clusterrolebinding.yaml
  - operator/deployment.yaml

