apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crd/birservice_crd.yaml
  - operator/namespace.yaml
  # github-pipeline-secret: one-time, artıq konfiqurasiya olunub
  - operator/serviceaccount.yaml
  - operator/clusterrole.yaml
  - operator/clusterrolebinding.yaml
  - operator/role-argocd-secrets.yaml
  - operator/deployment.yaml

