apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  {{- if .Values.istio.enabled }}
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint
  {{- end }}
