apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.clusterRole.name }}
rules:
{{- range $key, $rule := .Values.rbac.clusterRole.rules }}
{{- if $rule.enabled }}
  - apiGroups: {{ $rule.apiGroups | toJson }}
    resources: {{ $rule.resources | toJson }}
    verbs: {{ $rule.verbs | toJson }}
{{- end }}
{{- end }}
{{- range .Values.rbac.clusterRole.extraRules }}
  - apiGroups: {{ .apiGroups | toJson }}
    resources: {{ .resources | toJson }}
    verbs: {{ .verbs | toJson }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.clusterRoleBinding.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.clusterRole.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.argocdRole.name }}
  namespace: {{ .Values.rbac.argocdRole.namespace }}
rules:
{{- range $key, $rule := .Values.rbac.argocdRole.rules }}
{{- if $rule.enabled }}
  - apiGroups: {{ $rule.apiGroups | toJson }}
    resources: {{ $rule.resources | toJson }}
    verbs: {{ $rule.verbs | toJson }}
{{- end }}
{{- end }}
{{- range .Values.rbac.argocdRole.extraRules }}
  - apiGroups: {{ .apiGroups | toJson }}
    resources: {{ .resources | toJson }}
    verbs: {{ .verbs | toJson }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.argocdRoleBinding.name }}
  namespace: {{ .Values.rbac.argocdRole.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.rbac.argocdRole.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Release.Namespace }}
