{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webhook.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
  ports:
    - name: webhook
      port: {{ .Values.webhook.service.port }}
      targetPort: {{ .Values.webhook.service.targetPort }}
      protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.webhook.route.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/target: {{ .Values.webhook.route.targetIP | quote }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.webhook.gateway.name }}
      namespace: {{ .Values.webhook.gateway.namespace }}
      sectionName: {{ .Values.webhook.gateway.sectionName }}
  hostnames:
    - {{ .Values.webhook.route.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.webhook.route.pathPrefix }}
      backendRefs:
        - group: ""
          kind: Service
          name: {{ .Values.webhook.service.name }}
          port: {{ .Values.webhook.service.port }}
          weight: 1
{{- end }}
