# CRD + Operator — platform öz repo-sunda idarə olunur
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: easy-deploy-platform
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Murad-Suleymanov/BasePlate
      targetRevision: HEAD
      path: manifests/crd
    - repoURL: https://github.com/Murad-Suleymanov/BasePlate
      targetRevision: HEAD
      path: manifests/operator
  destination:
    server: https://kubernetes.default.svc
    namespace: easy-deploy-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
