apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: easy-deploy-birservices
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/Murad-Suleymanov/BasePlate
        revision: HEAD
        files:
          - path: "tenants/*/simple-yaml/*.yaml"
  template:
    metadata:
      name: '{{ printf "%s-%s" (index (splitList "/" .path.path) 1) (trimSuffix ".yaml" .path.filenameNormalized) }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Murad-Suleymanov/BasePlate
        targetRevision: HEAD
        path: charts/birservice
        helm:
          releaseName: '{{ .name }}'
          valueFiles:
            - '{{ printf "../../%s/%s" .path.path .path.filename }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ default (index (splitList "/" .path.path) 1) .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

