---
# Route: echo service (dev namespace)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo-route
  namespace: dev
spec:
  parentRefs:
    - name: main-gateway
      namespace: nginx-gateway
  hostnames:
    - "echo.easysolution.work"
  rules:
    - backendRefs:
        - name: echo-svc
          port: 8080
---
# Route: whoami service (dev namespace)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whoami-route
  namespace: dev
spec:
  parentRefs:
    - name: main-gateway
      namespace: nginx-gateway
  hostnames:
    - "whoami.easysolution.work"
  rules:
    - backendRefs:
        - name: whoami-svc
          port: 8080
---
# Route: Grafana (monitoring namespace)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-route
  namespace: monitoring
spec:
  parentRefs:
    - name: main-gateway
      namespace: nginx-gateway
  hostnames:
    - "grafana.easysolution.work"
  rules:
    - backendRefs:
        - name: monitoring-grafana
          port: 80
---
# Route: ArgoCD UI (argocd namespace)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-route
  namespace: argocd
spec:
  parentRefs:
    - name: main-gateway
      namespace: nginx-gateway
  hostnames:
    - "argocd.easysolution.work"
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
