---
# Allow the Gateway in nginx-gateway namespace to reference Services in dev namespace
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-to-dev
  namespace: dev
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: dev
  to:
    - group: ""
      kind: Service
---
# Allow the Gateway in nginx-gateway namespace to reference Services in monitoring namespace
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-to-monitoring
  namespace: monitoring
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: monitoring
  to:
    - group: ""
      kind: Service
---
# Allow the Gateway in nginx-gateway namespace to reference Services in argocd namespace
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-to-argocd
  namespace: argocd
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: argocd
  to:
    - group: ""
      kind: Service
